# refer: https://knowledge.udacity.com/questions/711557
- name: "install dependencies"
  become: true
  apt:
    name: tar
    state: latest
    update_cache: yes

- name: path storing web code
  become: true
  file:
    path: /home/web
    state: directory
    mode: 0755

- name: copy artifact to web directory
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/web/artifact.tar.gz

- name: uncompress
  become: true
  shell: |
    cd /home/web
    tar -vxf artifact.tar.gz
- name: build and start node
  shell: |
    cd /home/web
    npm install
    pm2 stop default
    pm2 start npm -- start