# refer: https://knowledge.udacity.com/questions/711557
- name: Create app folder
  become: true
  file:
    path: /home/ubuntu/app
    state: directory

- name: "Copy backend build to server"
  become: true
  unarchive:
    src: /tmp/workspace/backend.tar.gz
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Copy package.json to server"
  become: true
  copy:
    src: /tmp/workspace/package.json
    dest: /home/ubuntu/app/
    owner: ubuntu

- name: "Testing env variable"
  debug:
    msg: "My env variable is: '{{ lookup('env', 'TYPEORM_ENTITIES') }}'"

- name: "Install NPM dependencies"
  shell:
    cmd: npm install --production
    chdir: /home/ubuntu/app

- name: "Start backend with pm2"
  become: true
  shell: |
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    cd /home/ubuntu/app
    pm2 start main.js --name app
- name: "Set pm2 start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
